#!/bin/bash

# Script to manage Kubernetes cluster with kind
# Usage: k8s up|down

# Function to create the Kubernetes cluster
cluster_up() {

    echo "Installing Operator Lifecycle Manager..."
    curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/install.sh | bash -s v0.28.0

    echo "Installing or upgrading Helm chart for operator-subscriptions..."
    helm upgrade operator-subscriptions operator-subscriptions --install --namespace operator-subscriptions --create-namespace

    echo "Kubernetes cluster setup completed!"
}

# Function to delete the Kubernetes cluster
cluster_down() {
    echo "Deleting Kubernetes cluster with kind..."
    kind delete cluster --name k8s-quickstart

    echo "Kind cluster deleted successfully!"
}

# Function to display help message
display_help() {
    echo "Usage: $0 up|down"
    echo "Manage Kubernetes cluster with kind."
    echo
    echo "Options:"
    echo "  up      Start the Kubernetes cluster"
    echo "  down    Stop the Kubernetes cluster"
    echo "  -h, --help  Display this help message"
}

# Check for argument
if [ -z "$1" ]; then
    echo "Error: No argument provided."
    display_help
    exit 1
fi

# Execute the appropriate function based on the argument
case "$1" in
    up)
        cluster_up
        ;;
    down)
        cluster_down
        ;;
    -h|--help)
        display_help
        ;;
    *)
        echo "Invalid argument: $1"
        display_help
        exit 1
        ;;
esac
