---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-azure-service-operator
  namespace: operators
spec:
  channel: stable
  name: azure-service-operator
  source: operatorhubio-catalog
  sourceNamespace: olm