{{- if .Values.features.flagsmith }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-flagsmith
  namespace: operators
spec:
  channel: stable
  name: flagsmith
  source: operatorhubio-catalog
  sourceNamespace: olm
{{- end }}
