apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-keda
  namespace: operators
spec:
  channel: stable
  name: keda
  source: operatorhubio-catalog
  sourceNamespace: olm