{{- if .Values.features.kubemod }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-kubemod
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-kubemod
spec:
  targetNamespaces:
  - my-kubemod
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-kubemod
  namespace: my-kubemod
spec:
  channel: beta
  name: kubemod
  source: operatorhubio-catalog
  sourceNamespace: olm

{{- end }}
