{{- if .Values.features.neuvector }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: my-neuvector-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: my-neuvector-operator
spec:
  targetNamespaces:
  - my-neuvector-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-neuvector-operator
  namespace: my-neuvector-operator
spec:
  channel: beta
  name: neuvector-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
{{- end }}
