---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-self-node-remediation
  namespace: operators
spec:
  channel: stable
  name: self-node-remediation
  source: operatorhubio-catalog
  sourceNamespace: olm