---
- name: Configure and Deploy OKD VMs
  hosts: kvm_host
  become: true
  vars_files:
    - ../vars.yaml

  tasks:
    - name: Create VLAN for OKD Cluster
      command: >
        nmcli connection add type vlan con-name okd-cluster-vlan
        dev {{ common_vm_config.network_bridge }} id {{ vlan_id }}
      ignore_errors: yes

    - name: Create and Configure VMs
      loop: "{{ vm_definitions }}"
      shell: |
        virt-install \
          --name {{ item.name }} \
          --memory {{ item.ram }} \
          --vcpus {{ common_vm_config.vcpu }} \
          --disk path=/var/lib/libvirt/images/{{ item.name }}.qcow2,size={{ item.storage }},format=qcow2 \
          --cdrom {{ common_vm_config.iso_path }} \
          --network bridge={{ common_vm_config.network_bridge }},model=virtio \
          --os-type linux \
          --os-variant fedora-coreos-stable \
          --graphics none \
          --noautoconsole \
          --wait -1
      args:
        executable: /bin/bash
      register: output