---
- name: Destroy OKD VMs and Clean Up Resources
  hosts: kvm_host
  become: true
  vars_files:
    - ../vars.yaml

  tasks:
    - name: Stop and undefine VMs
      loop: "{{ vm_definitions }}"
      shell: |
        virsh destroy {{ item.name }} || true
        virsh undefine {{ item.name }} --remove-all-storage || true
      args:
        executable: /bin/bash

    - name: Remove VLAN using nmcli
      command: >
        nmcli connection delete okd-cluster-vlan
      ignore_errors: yes
