---
- name: Destroy OKD VMs and Clean Up Resources
  hosts: kvm_host
  vars_files:
    - okd_vm_vars.yml

  tasks:
    - name: Stop and Remove VMs
      loop: "{{ vm_definitions }}"
      community.libvirt.libvirt_domain:
        name: "{{ item.name }}"
        state: absent
        uri: "qemu:///system"

    - name: Remove VM storage
      loop: "{{ vm_definitions }}"
      community.libvirt.libvirt_volume:
        name: "{{ item.name }}.qcow2"
        pool: default
        state: absent

    - name: Remove VLAN for OKD Cluster
      community.network.vlan:
        vlan_id: "{{ vlan_id }}"
        name: "okd-cluster-vlan"
        state: absent
        bridge: "{{ common_vm_config.network_bridge }}"
