# values.yaml

features:
  argocd: false
  azure-service-operator: false
  cert-manager: false
  dapr: false
  elastic: false
  flagsmith: false
  grafana: false
  kafka: false
  keda: false
  keycloak: false
  kiali: false
  kubemod: false
  kubevirt: false
  minio: false
  mongodb: false
  neuvector: false
  node-maintenance: false
  node-self-remediation: false
  postgres: false
  prometheus: false
  rabbitmq: false
  redis: false
  tekton: false
  trivy: false
  vault: false

