---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-cleanup-sa
  namespace: {{ .Release.Namespace }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-deleter-binding
subjects:
- kind: ServiceAccount
  name: namespace-cleanup-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-olm-job-{{ randAlphaNum 5 | lower }}
  namespace: default
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  template:
    spec:
      serviceAccountName: namespace-cleanup-sa
      restartPolicy: Never
      containers:
      - name: cleanup
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args:
        - >
          echo "Removing finalizers from 'operators' and 'olm' namespaces..." &&
          kubectl patch namespace operators -p '{"metadata":{"finalizers":null}}' --type=merge &&
          kubectl patch namespace olm -p '{"metadata":{"finalizers":null}}' --type=merge &&
          echo "Deleting 'operators' and 'olm' namespaces..." &&
          kubectl delete namespace operators --wait=false &&
          kubectl delete namespace olm --wait=false &&
          echo "Namespaces deleted forcefully"
        securityContext:
          runAsUser: 0
