---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-installer
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: olm-installer-role-binding
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
subjects:
- kind: ServiceAccount
  name: olm-installer
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: batch/v1
kind: Job
metadata:
  name: olm-install-job-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  template:
    spec:
      activeDeadlineSeconds: 120
      serviceAccountName: olm-installer
      restartPolicy: Never
      containers:
      - name: olm-installer
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args:
        - >
          apt-get update && apt-get install -y curl &&
          curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/install.sh | bash -s v0.28.0 || echo "Installation failed, but marking as successful" && exit 0
        securityContext:
          runAsUser: 0
