---
- name: Generate SSH keys if they don't exist
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if SSH key exists
      stat:
        path: ~/.ssh/id_rsa.pub
      register: ssh_key

    - name: Generate SSH key
      command: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''
      when: not ssh_key.stat.exists

- name: Copy SSH key to VMs
  hosts: masters,workers
  become: true
  vars_files:
    - ../vars.yaml

  tasks:
    - name: Ensure authorized_keys directory exists
      file:
        path: "/home/{{ ansible_ssh_user }}/.ssh"
        state: directory
        mode: '0700'

    - name: Copy SSH public key to authorized_keys
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ public_key }}"
